
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '**'

# GitHub Actions workflow to deploy to Azure using azd
# To configure required secrets for connecting to Azure, simply run `azd pipeline config`
# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the backend
        run: |
          docker build -t marketing-backend -f samples/marketing/backend/Dockerfile .
        shell: pwsh

      - name: Build the frontend
        run: |
          cd samples/marketing/frontend/
          docker build -t marketing-frontend .
        shell: pwsh