
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the backend
        run: |
          docker build -t marketing-backend -f samples/marketing/backend/Dockerfile .
        shell: pwsh

      - name: Build the frontend
        run: |
          cd samples/marketing/frontend/
          docker build -t marketing-frontend .
        shell: pwsh